In [1]:
import numpy as np

## 1. Calculating Total Revenue

In [2]:
prices = np.array([19.99,29.99,14.99, 9.99,24.99])
prices

array([19.99, 29.99, 14.99,  9.99, 24.99])

In [3]:
quantities = np.array([10,5,8,12,3])
quantities

array([10,  5,  8, 12,  3])

In [4]:
revenue_per_product = prices * quantities
revenue_per_product

array([199.9 , 149.95, 119.92, 119.88,  74.97])

In [5]:
total_revenue = np.sum(revenue_per_product)
total_revenue

np.float64(664.62)