In [1]:
import numpy as np

In [3]:
first = np.array([[1,2,3], [4,5,6]])
first

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
first.shape

(2, 3)

In [5]:
second = np.array([[7,8,9], [10,11,12]])
second

array([[ 7,  8,  9],
       [10, 11, 12]])

In [6]:
second.shape

(2, 3)

In [7]:
first + second

array([[ 8, 10, 12],
       [14, 16, 18]])

In [9]:
first[1,1]

np.int64(5)

In [10]:
np.concatenate((first, second))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])